services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_node
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app # Monter les fichiers locaux pour le développement en direct
      - /app/node_modules # Empêcher les conflits entre l'hôte et le conteneur
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_node
    ports:
      - '9876:9876'
    volumes:
      - ./backend:/app
      # - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
