import Navbar from '@/components/layout/Navbar';
import Banner from '@/components/layout/Banner';
import Footer from '@/components/layout/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/globals.css';
import { ProductProvider } from '@/context/ProductContext';

export const metadata = {
  title: 'Worthy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://kit.fontawesome.com/0433bfbe12.js"
          crossOrigin="anonymous"
          async
        ></script>
      </head>
      <body>
        <Banner />
        <Navbar />
        <ProductProvider>{children}</ProductProvider>
        <Footer />
      </body>
    </html>
  );
}
